[workspace]
members = ["apps/baho-cli", "apps/baho-gui", "crates/baho-core", "crates/baho-exec", "crates/baho-ingest", "crates/baho-ingest-csv", "crates/baho-llm", "crates/baho-model", "crates/baho-plan", "crates/baho-run"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"
